import QtQuick 2.15

Item {
    property var colors: {
        '3ds': '#73bc9e',
        'allgames': '#292463',
        'android': '#266f4f',
        'arcade': '#528821',
        'dreamcast': '#2387ff',
        'favorites': '#b75057',
        'gamecube': '#4b0082',
        'gamegear': '#d0970d',
        'gb': '#9f75b0',
        'gba': '#342692',
        'gbc': '#7b4ccc',
        'genesis': '#df535b',
        'lynx': '#4c9141',
        'mastersystem': '#2f34c2',
        'megadrive': '#df535b',
        'n64': '#807c68',
        'nds': '#d09826',
        'neogeo': '#1499de',
        'neogeocd': '#9e5c27',
        'nes': '#c85173',
        'ngp': '#aa6aff',
        'pcengine': '#25482b',
        'pico8': '#1c542d',
        'pokemini': '#19b091',
        'ports': '#1d334a',
        'ps2': '#347867',
        'psp': '#4e0b9c',
        'psx': '#365f8d',
        'recents': '#906226',
        'saturn': '#5b92ff',
        'sega32x': '#6935e9',
        'segacd': '#cc4545',
        'snes': '#aa6aff',
        'tg16': '#25482b',
        'vboy': '#802325',
        'wii': '#e0e027',
        'wswan': '#d38aba',
        'wswanc': '#9b3f23',
        'default': '#194492',
    };

    property var companies: {
        '3ds': 'Nintendo',
        'allgames': '',
        'android': '',
        'arcade': '',
        'dreamcast': 'Sega',
        'favorites': '',
        'gamecube': 'Nintendo',
        'gamegear': 'Sega',
        'gb': 'Nintendo',
        'gba': 'Nintendo',
        'gbc': 'Nintendo',
        'genesis': 'Sega',
        'lynx': 'Atari',
        'mastersystem': 'Sega',
        'megadrive': 'Sega',
        'n64': 'Nintendo',
        'nds': 'Nintendo',
        'neogeo': 'SNK',
        'neogeocd': 'SNK',
        'nes': 'Nintendo',
        'ngp': 'SNK',
        'pcengine': 'NEC',
        'pico8': 'Lexaloffle',
        'pokemini': 'Nintendo',
        'ports': '',
        'ps2': 'Sony',
        'psp': 'Sony',
        'psx': 'Sony',
        'recents': '',
        'saturn': 'Sega',
        'sega32x': 'Sega',
        'segacd': 'Sega',
        'snes': 'Nintendo',
        'tg16': 'NEC',
        'vboy': 'Nintendo',
        'wii': 'Nintendo',
        'wswan': 'Bandai',
        'wswanc': 'Bandai',
    };
}
