import QtQuick 2.15

Item {
    property var colors: {
        'gamecube': '#4b0082',
        '3ds': '#b70297',
        'arcade': '#b87333',
        'pokemini': '#40cab5',
        'saturn': '#5b92ff',
        'vboy': '#c60427',
        'wswan': '#347867',
        'wswanc': '#e0e027',
        'ps2': '#2125a5',
        'gg': '#011da9',
        'gamegear': '#ffaa22',
        'snes': '#aa6aff',
        'ngp': '#aa6aff',
        'genesis': '#df535b',
        'neogeo': '#1499de',
        'android': '#266f4f',
        'mastersystem': '#2f34c2',
        'neogeocd': '#efc323',
        'gb': '#1da1dc',
        'gba': '#342692',
        'gbc': '#7b4ccc',
        'pcengine': '#ff955b',
        'tg16': '#ff955b',
        'nes': '#c85173',
        'n64': '#ff5b5b',
        'nds': '#efc323',
        'psx': '#f0cc40',
        'sega32x': '#6935e9',
        'segacd': '#c85173',
        'dreamcast': '#2387ff',
        'psp': '#4e0b9c',
        'default': '#2387ff',
    };

    property var companies: {
        'arcade': 'Various',
        'wswan': 'Bandai',
        'wswanc': 'Bandai',
        'dreamcast': 'Sega',
        'gg': 'Sega',
        'gamegear': 'Sega',
        'genesis': 'Sega',
        'megadrive': 'Sega',
        'segacd': 'Sega',
        'megacd': 'Sega',
        'mastersystem': 'Sega',
        'sega32x': 'Sega',
        'saturn': 'Sega',
        'neogeo': 'SNK',
        'neogeocd': 'SNK',
        'ngp': 'SNK',
        'gamecube': 'Nintendo',
        'gb': 'Nintendo',
        'gba': 'Nintendo',
        'gbc': 'Nintendo',
        'pokemini': 'Nintendo',
        'snes': 'Nintendo',
        'nes': 'Nintendo',
        'n64': 'Nintendo',
        'nds': 'Nintendo',
        '3ds': 'Nintendo',
        'vboy': 'Nintendo',
        'pcengine': 'NEC',
        'tg16': 'NEC',
        'psx': 'Sony',
        'psp': 'Sony',
        'ps2': 'Sony',
    };
}
