import QtQuick 2.15

Item {
    property var systemColors: {
        'gamecube': '#4B0082',
        '3ds': '#B70297',
        'arcade': '#B87333',
        'pokemini': '#40CAB5',
        'saturn': '#5B92FF',
        'vboy': '#C60427',
        'wswan': '#347867',
        'wswanc': '#E0E027',
        'ps2': '#2125A5',
        'gg': '#011DA9',
        'gamegear': '#FFAA22',
        'snes': '#AA6AFF',
        'ngp': '#AA6AFF',
        'genesis': '#DF535B',
        'neogeo': '#1499DE',
        'android': '#266F4F',
        'mastersystem': '#2F34C2',
        'neogeocd': '#EFC323',
        'gb': '#1DA1DC',
        'gba': '#342692',
        'gbc': '#7B4CCC',
        'pcengine': '#FF955B',
        'tg16': '#FF955B',
        'nes': '#C85173',
        'n64': '#FF5B5B',
        'nds': '#EFC323',
        'psx': '#F0CC40',
        'sega32x': '#6935E9',
        'segacd': '#C85173',
        'dreamcast': '#2387FF',
        'psp': '#4E0B9C',
        'default': '#2387FF',
    };

    property var systemCompanies: {
        'arcade': 'Various',
        'wswan': 'Bandai',
        'wswanc': 'Bandai',
        'dreamcast': 'Sega',
        'gg': 'Sega',
        'gamegear': 'Sega',
        'genesis': 'Sega',
        'megadrive': 'Sega',
        'segacd': 'Sega',
        'megacd': 'Sega',
        'mastersystem': 'Sega',
        'sega32x': 'Sega',
        'saturn': 'Sega',
        'neogeo': 'SNK',
        'neogeocd': 'SNK',
        'ngp': 'SNK',
        'gamecube': 'Nintendo',
        'gb': 'Nintendo',
        'gba': 'Nintendo',
        'gbc': 'Nintendo',
        'pokemini': 'Nintendo',
        'snes': 'Nintendo',
        'nes': 'Nintendo',
        'n64': 'Nintendo',
        'nds': 'Nintendo',
        '3ds': 'Nintendo',
        'vboy': 'Nintendo',
        'pcengine': 'NEC',
        'tg16': 'NEC',
        'psx': 'Sony',
        'psp': 'Sony',
        'ps2': 'Sony',
    };
}
